[package]
name = "portainer-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "portainer-cli"
path = "src/main.rs"

[dependencies]
portainer-lib = { path = "../portainer-lib" }
clap = { version = "4.4", features = ["derive"] }
